module.exports.matchInfo = {
    "seasonId": 9,
    "queueId": 400,
    "gameId": 2678337242,
    "participantIdentities": [
    {
        "player": {
            "currentPlatformId": "NA1",
            "summonerName": "SonOfKorhal",
            "matchHistoryUri": "/v1/stats/player_history/NA/33282562",
            "platformId": "NA",
            "currentAccountId": 33282562,
            "profileIcon": 3233,
            "summonerId": 20377731,
            "accountId": 33282562
        },
        "participantId": 1
    },
    {
        "player": {
            "currentPlatformId": "NA1",
            "summonerName": "zSpectrum",
            "matchHistoryUri": "/v1/stats/player_history/NA1/228610628",
            "platformId": "NA1",
            "currentAccountId": 228610628,
            "profileIcon": 3232,
            "summonerId": 67164581,
            "accountId": 228610628
        },
        "participantId": 2
    },
    {
        "player": {
            "currentPlatformId": "NA1",
            "summonerName": "Extend",
            "matchHistoryUri": "/v1/stats/player_history/NA/34732393",
            "platformId": "NA",
            "currentAccountId": 34732393,
            "profileIcon": 3219,
            "summonerId": 21368061,
            "accountId": 34732393
        },
        "participantId": 3
    },
    {
        "player": {
            "currentPlatformId": "NA1",
            "summonerName": "JigglyJuggz",
            "matchHistoryUri": "/v1/stats/player_history/NA1/233982199",
            "platformId": "NA1",
            "currentAccountId": 233982199,
            "profileIcon": 1116,
            "summonerId": 77221973,
            "accountId": 233982199
        },
        "participantId": 4
    },
    {
        "player": {
            "currentPlatformId": "NA1",
            "summonerName": "jayblayze",
            "matchHistoryUri": "/v1/stats/player_history/NA1/43916265",
            "platformId": "NA1",
            "currentAccountId": 43916265,
            "profileIcon": 3232,
            "summonerId": 76229139,
            "accountId": 43916265
        },
        "participantId": 5
    },
    {
        "player": {
            "currentPlatformId": "NA1",
            "summonerName": "KaneLW",
            "matchHistoryUri": "/v1/stats/player_history/NA1/201334531",
            "platformId": "NA1",
            "currentAccountId": 201334531,
            "profileIcon": 588,
            "summonerId": 38365661,
            "accountId": 201334531
        },
        "participantId": 6
    },
    {
        "player": {
            "currentPlatformId": "NA1",
            "summonerName": "Living Shádow ",
            "matchHistoryUri": "/v1/stats/player_history/NA1/211844345",
            "platformId": "NA1",
            "currentAccountId": 211844345,
            "profileIcon": 3232,
            "summonerId": 48769266,
            "accountId": 211844345
        },
        "participantId": 7
    },
    {
        "player": {
            "currentPlatformId": "NA1",
            "summonerName": "stryderjzw",
            "matchHistoryUri": "/v1/stats/player_history/NA/285458",
            "platformId": "NA",
            "currentAccountId": 285458,
            "profileIcon": 3187,
            "summonerId": 258622,
            "accountId": 285458
        },
        "participantId": 8
    },
    {
        "player": {
            "currentPlatformId": "NA1",
            "summonerName": "BFY Meowington",
            "matchHistoryUri": "/v1/stats/player_history/NA1/215942119",
            "platformId": "NA1",
            "currentAccountId": 215942119,
            "profileIcon": 3231,
            "summonerId": 53300045,
            "accountId": 215942119
        },
        "participantId": 9
    },
    {
        "player": {
            "currentPlatformId": "NA1",
            "summonerName": "XxIronJxX",
            "matchHistoryUri": "/v1/stats/player_history/NA1/202126603",
            "platformId": "NA1",
            "currentAccountId": 202126603,
            "profileIcon": 2095,
            "summonerId": 39291441,
            "accountId": 202126603
        },
        "participantId": 10
    }
],
    "gameVersion": "7.24.212.5337",
    "platformId": "NA1",
    "gameMode": "CLASSIC",
    "mapId": 11,
    "gameType": "MATCHED_GAME",
    "teams": [
    {
        "firstDragon": false,
        "bans": [
            {
                "pickTurn": 1,
                "championId": 89
            },
            {
                "pickTurn": 2,
                "championId": 420
            },
            {
                "pickTurn": 3,
                "championId": 53
            },
            {
                "pickTurn": 4,
                "championId": 81
            },
            {
                "pickTurn": 5,
                "championId": 157
            }
        ],
        "firstInhibitor": false,
        "win": "Fail",
        "firstRiftHerald": false,
        "firstBaron": false,
        "baronKills": 0,
        "riftHeraldKills": 0,
        "firstBlood": false,
        "teamId": 100,
        "firstTower": false,
        "vilemawKills": 0,
        "inhibitorKills": 0,
        "towerKills": 0,
        "dominionVictoryScore": 0,
        "dragonKills": 0
    },
    {
        "firstDragon": true,
        "bans": [
            {
                "pickTurn": 6,
                "championId": 90
            },
            {
                "pickTurn": 7,
                "championId": 81
            },
            {
                "pickTurn": 8,
                "championId": 61
            },
            {
                "pickTurn": 9,
                "championId": 238
            },
            {
                "pickTurn": 10,
                "championId": 80
            }
        ],
        "firstInhibitor": true,
        "win": "Win",
        "firstRiftHerald": false,
        "firstBaron": false,
        "baronKills": 0,
        "riftHeraldKills": 0,
        "firstBlood": true,
        "teamId": 200,
        "firstTower": true,
        "vilemawKills": 0,
        "inhibitorKills": 3,
        "towerKills": 11,
        "dominionVictoryScore": 0,
        "dragonKills": 3
    }
],
    "participants": [
    {
        "stats": {
            "neutralMinionsKilledTeamJungle": 63,
            "visionScore": 53,
            "magicDamageDealtToChampions": 50,
            "largestMultiKill": 1,
            "totalTimeCrowdControlDealt": 526,
            "longestTimeSpentLiving": 368,
            "perk1Var1": 153,
            "perk1Var3": 0,
            "perk1Var2": 0,
            "tripleKills": 0,
            "perk5": 8134,
            "perk4": 8136,
            "playerScore9": 0,
            "playerScore8": 0,
            "kills": 2,
            "playerScore1": 0,
            "playerScore0": 0,
            "playerScore3": 0,
            "playerScore2": 0,
            "playerScore5": 0,
            "playerScore4": 0,
            "playerScore7": 0,
            "playerScore6": 0,
            "perk5Var1": 3,
            "perk5Var3": 0,
            "perk5Var2": 0,
            "totalScoreRank": 0,
            "neutralMinionsKilled": 84,
            "damageDealtToTurrets": 1297,
            "physicalDamageDealtToChampions": 4908,
            "damageDealtToObjectives": 1297,
            "perk2Var2": 28,
            "perk2Var3": 0,
            "totalUnitsHealed": 1,
            "perk2Var1": 21,
            "perk4Var1": 16,
            "totalDamageTaken": 24331,
            "perk4Var3": 0,
            "wardsKilled": 10,
            "largestCriticalStrike": 0,
            "largestKillingSpree": 0,
            "quadraKills": 0,
            "magicDamageDealt": 2045,
            "firstBloodAssist": false,
            "item2": 2032,
            "item3": 1042,
            "item0": 1419,
            "item1": 3153,
            "item6": 3364,
            "item4": 3111,
            "item5": 0,
            "perk1": 9111,
            "perk0": 8008,
            "perk3": 8014,
            "perk2": 9104,
            "perk3Var3": 0,
            "perk3Var2": 0,
            "perk3Var1": 166,
            "damageSelfMitigated": 11583,
            "magicalDamageTaken": 9431,
            "perk0Var2": 0,
            "firstInhibitorKill": false,
            "trueDamageTaken": 1310,
            "assists": 1,
            "perk4Var2": 0,
            "goldSpent": 7900,
            "trueDamageDealt": 10425,
            "participantId": 1,
            "physicalDamageDealt": 85525,
            "sightWardsBoughtInGame": 0,
            "totalDamageDealtToChampions": 6478,
            "physicalDamageTaken": 13590,
            "totalPlayerScore": 0,
            "win": false,
            "objectivePlayerScore": 0,
            "totalDamageDealt": 97997,
            "neutralMinionsKilledEnemyJungle": 0,
            "deaths": 11,
            "wardsPlaced": 27,
            "perkPrimaryStyle": 8000,
            "perkSubStyle": 8100,
            "turretKills": 0,
            "firstBloodKill": false,
            "trueDamageDealtToChampions": 1519,
            "goldEarned": 8246,
            "killingSprees": 0,
            "unrealKills": 0,
            "firstTowerAssist": false,
            "firstTowerKill": false,
            "champLevel": 12,
            "doubleKills": 0,
            "inhibitorKills": 0,
            "firstInhibitorAssist": false,
            "perk0Var1": 45,
            "combatPlayerScore": 0,
            "perk0Var3": 0,
            "visionWardsBoughtInGame": 1,
            "pentaKills": 0,
            "totalHeal": 4293,
            "totalMinionsKilled": 72,
            "timeCCingOthers": 3
        },
        "spell1Id": 6,
        "participantId": 1,
        "highestAchievedSeasonTier": "SILVER",
        "spell2Id": 11,
        "teamId": 100,
        "timeline": {
            "lane": "JUNGLE",
            "participantId": 1,
            "csDiffPerMinDeltas": {
                "0-10": 1.4,
                "10-20": 2.3
            },
            "goldPerMinDeltas": {
                "0-10": 249.4,
                "10-20": 318.1
            },
            "xpDiffPerMinDeltas": {
                "0-10": 20,
                "10-20": -259.90000000000003
            },
            "creepsPerMinDeltas": {
                "0-10": 1.4,
                "10-20": 4
            },
            "xpPerMinDeltas": {
                "0-10": 335.1,
                "10-20": 376.2
            },
            "role": "NONE",
            "damageTakenDiffPerMinDeltas": {
                "0-10": -79.30000000000001,
                "10-20": 20.5
            },
            "damageTakenPerMinDeltas": {
                "0-10": 485.9,
                "10-20": 830.3
            }
        },
        "championId": 11
    },
    {
        "stats": {
            "neutralMinionsKilledTeamJungle": 0,
            "visionScore": 39,
            "magicDamageDealtToChampions": 6441,
            "largestMultiKill": 0,
            "totalTimeCrowdControlDealt": 144,
            "longestTimeSpentLiving": 711,
            "perk1Var1": 1414,
            "perk1Var3": 0,
            "perk1Var2": 0,
            "tripleKills": 0,
            "perk5": 8321,
            "perk4": 8345,
            "playerScore9": 0,
            "playerScore8": 0,
            "kills": 0,
            "playerScore1": 0,
            "playerScore0": 0,
            "playerScore3": 0,
            "playerScore2": 0,
            "playerScore5": 0,
            "playerScore4": 0,
            "playerScore7": 0,
            "playerScore6": 0,
            "perk5Var1": 3,
            "perk5Var3": 0,
            "perk5Var2": 0,
            "totalScoreRank": 0,
            "neutralMinionsKilled": 0,
            "damageDealtToTurrets": 0,
            "physicalDamageDealtToChampions": 1175,
            "damageDealtToObjectives": 0,
            "perk2Var2": 0,
            "perk2Var3": 0,
            "totalUnitsHealed": 5,
            "perk2Var1": 19,
            "perk4Var1": 4,
            "totalDamageTaken": 15312,
            "perk4Var3": 0,
            "wardsKilled": 6,
            "largestCriticalStrike": 0,
            "largestKillingSpree": 0,
            "quadraKills": 0,
            "magicDamageDealt": 11890,
            "firstBloodAssist": false,
            "item2": 3158,
            "item3": 3114,
            "item0": 3107,
            "item1": 2301,
            "item6": 3364,
            "item4": 0,
            "item5": 0,
            "perk1": 8226,
            "perk0": 8214,
            "perk3": 8237,
            "perk2": 8210,
            "perk3Var3": 0,
            "perk3Var2": 0,
            "perk3Var1": 404,
            "damageSelfMitigated": 5806,
            "magicalDamageTaken": 5848,
            "perk0Var2": 1010,
            "firstInhibitorKill": false,
            "trueDamageTaken": 212,
            "assists": 5,
            "perk4Var2": 0,
            "goldSpent": 6300,
            "trueDamageDealt": 668,
            "participantId": 2,
            "physicalDamageDealt": 2575,
            "sightWardsBoughtInGame": 0,
            "totalDamageDealtToChampions": 8286,
            "physicalDamageTaken": 9250,
            "totalPlayerScore": 0,
            "win": false,
            "objectivePlayerScore": 0,
            "totalDamageDealt": 15135,
            "neutralMinionsKilledEnemyJungle": 0,
            "deaths": 5,
            "wardsPlaced": 18,
            "perkPrimaryStyle": 8200,
            "perkSubStyle": 8300,
            "turretKills": 0,
            "firstBloodKill": false,
            "trueDamageDealtToChampions": 668,
            "goldEarned": 6734,
            "killingSprees": 0,
            "unrealKills": 0,
            "firstTowerAssist": false,
            "firstTowerKill": false,
            "champLevel": 11,
            "doubleKills": 0,
            "inhibitorKills": 0,
            "firstInhibitorAssist": false,
            "perk0Var1": 576,
            "combatPlayerScore": 0,
            "perk0Var3": 0,
            "visionWardsBoughtInGame": 2,
            "pentaKills": 0,
            "totalHeal": 9715,
            "totalMinionsKilled": 11,
            "timeCCingOthers": 37
        },
        "spell1Id": 4,
        "participantId": 2,
        "highestAchievedSeasonTier": "PLATINUM",
        "spell2Id": 3,
        "teamId": 100,
        "timeline": {
            "lane": "BOTTOM",
            "participantId": 2,
            "csDiffPerMinDeltas": {
                "0-10": -0.95,
                "10-20": -2.55
            },
            "goldPerMinDeltas": {
                "0-10": 137.10000000000002,
                "10-20": 254.3
            },
            "xpDiffPerMinDeltas": {
                "0-10": 4.499999999999986,
                "10-20": -214.15000000000003
            },
            "creepsPerMinDeltas": {
                "0-10": 0.1,
                "10-20": 0.6
            },
            "xpPerMinDeltas": {
                "0-10": 250.60000000000002,
                "10-20": 264.9
            },
            "role": "DUO_SUPPORT",
            "damageTakenDiffPerMinDeltas": {
                "0-10": 26.5,
                "10-20": 118.80000000000001
            },
            "damageTakenPerMinDeltas": {
                "0-10": 193.9,
                "10-20": 522.5
            }
        },
        "championId": 267
    },
    {
        "stats": {
            "neutralMinionsKilledTeamJungle": 12,
            "visionScore": 10,
            "magicDamageDealtToChampions": 15869,
            "largestMultiKill": 1,
            "totalTimeCrowdControlDealt": 58,
            "longestTimeSpentLiving": 657,
            "perk1Var1": 0,
            "perk1Var3": 0,
            "perk1Var2": 0,
            "tripleKills": 0,
            "perk5": 8236,
            "perk4": 8243,
            "playerScore9": 0,
            "playerScore8": 0,
            "kills": 5,
            "playerScore1": 0,
            "playerScore0": 0,
            "playerScore3": 0,
            "playerScore2": 0,
            "playerScore5": 0,
            "playerScore4": 0,
            "playerScore7": 0,
            "playerScore6": 0,
            "perk5Var1": 24,
            "perk5Var3": 0,
            "perk5Var2": 0,
            "totalScoreRank": 0,
            "neutralMinionsKilled": 12,
            "damageDealtToTurrets": 186,
            "physicalDamageDealtToChampions": 947,
            "damageDealtToObjectives": 186,
            "perk2Var2": 3,
            "perk2Var3": 0,
            "totalUnitsHealed": 1,
            "perk2Var1": 9,
            "perk4Var1": 9,
            "totalDamageTaken": 24947,
            "perk4Var3": 0,
            "wardsKilled": 1,
            "largestCriticalStrike": 680,
            "largestKillingSpree": 2,
            "quadraKills": 0,
            "magicDamageDealt": 125253,
            "firstBloodAssist": false,
            "item2": 3070,
            "item3": 3151,
            "item0": 3157,
            "item1": 3027,
            "item6": 3364,
            "item4": 3020,
            "item5": 0,
            "perk1": 8313,
            "perk0": 8326,
            "perk3": 8347,
            "perk2": 8304,
            "perk3Var3": 0,
            "perk3Var2": 0,
            "perk3Var1": 0,
            "damageSelfMitigated": 11729,
            "magicalDamageTaken": 17111,
            "perk0Var2": 0,
            "firstInhibitorKill": false,
            "trueDamageTaken": 1188,
            "assists": 2,
            "perk4Var2": 0,
            "goldSpent": 10275,
            "trueDamageDealt": 533,
            "participantId": 3,
            "physicalDamageDealt": 16470,
            "sightWardsBoughtInGame": 0,
            "totalDamageDealtToChampions": 17094,
            "physicalDamageTaken": 6646,
            "totalPlayerScore": 0,
            "win": false,
            "objectivePlayerScore": 0,
            "totalDamageDealt": 142256,
            "neutralMinionsKilledEnemyJungle": 0,
            "deaths": 4,
            "wardsPlaced": 4,
            "perkPrimaryStyle": 8300,
            "perkSubStyle": 8200,
            "turretKills": 0,
            "firstBloodKill": false,
            "trueDamageDealtToChampions": 277,
            "goldEarned": 10491,
            "killingSprees": 2,
            "unrealKills": 0,
            "firstTowerAssist": false,
            "firstTowerKill": false,
            "champLevel": 15,
            "doubleKills": 0,
            "inhibitorKills": 0,
            "firstInhibitorAssist": false,
            "perk0Var1": 4,
            "combatPlayerScore": 0,
            "perk0Var3": 0,
            "visionWardsBoughtInGame": 1,
            "pentaKills": 0,
            "totalHeal": 4405,
            "totalMinionsKilled": 216,
            "timeCCingOthers": 19
        },
        "spell1Id": 4,
        "participantId": 3,
        "highestAchievedSeasonTier": "SILVER",
        "spell2Id": 6,
        "teamId": 100,
        "timeline": {
            "lane": "TOP",
            "participantId": 3,
            "csDiffPerMinDeltas": {
                "0-10": -0.4000000000000008,
                "10-20": -0.1999999999999993
            },
            "goldPerMinDeltas": {
                "0-10": 274,
                "10-20": 430.6
            },
            "xpDiffPerMinDeltas": {
                "0-10": -19.19999999999999,
                "10-20": 94.70000000000005
            },
            "creepsPerMinDeltas": {
                "0-10": 7.199999999999999,
                "10-20": 8.4
            },
            "xpPerMinDeltas": {
                "0-10": 420.7,
                "10-20": 664.3
            },
            "role": "SOLO",
            "damageTakenDiffPerMinDeltas": {
                "0-10": 15.899999999999991,
                "10-20": 232.40000000000003
            },
            "damageTakenPerMinDeltas": {
                "0-10": 303.3,
                "10-20": 873.2
            }
        },
        "championId": 13
    },
    {
        "stats": {
            "neutralMinionsKilledTeamJungle": 1,
            "visionScore": 16,
            "magicDamageDealtToChampions": 2896,
            "largestMultiKill": 0,
            "totalTimeCrowdControlDealt": 176,
            "longestTimeSpentLiving": 820,
            "perk1Var1": 103,
            "perk1Var3": 0,
            "perk1Var2": 0,
            "tripleKills": 0,
            "perk5": 8135,
            "perk4": 8139,
            "playerScore9": 0,
            "playerScore8": 0,
            "kills": 0,
            "playerScore1": 0,
            "playerScore0": 0,
            "playerScore3": 0,
            "playerScore2": 0,
            "playerScore5": 0,
            "playerScore4": 0,
            "playerScore7": 0,
            "playerScore6": 0,
            "perk5Var1": 1,
            "perk5Var3": 0,
            "perk5Var2": 0,
            "totalScoreRank": 0,
            "neutralMinionsKilled": 4,
            "damageDealtToTurrets": 293,
            "physicalDamageDealtToChampions": 5632,
            "damageDealtToObjectives": 293,
            "perk2Var2": 0,
            "perk2Var3": 0,
            "totalUnitsHealed": 2,
            "perk2Var1": 0,
            "perk4Var1": 776,
            "totalDamageTaken": 21458,
            "perk4Var3": 0,
            "wardsKilled": 3,
            "largestCriticalStrike": 152,
            "largestKillingSpree": 0,
            "quadraKills": 0,
            "magicDamageDealt": 11644,
            "firstBloodAssist": false,
            "item2": 3133,
            "item3": 3006,
            "item0": 1055,
            "item1": 3124,
            "item6": 3340,
            "item4": 1042,
            "item5": 1051,
            "perk1": 9111,
            "perk0": 8005,
            "perk3": 8014,
            "perk2": 9104,
            "perk3Var3": 0,
            "perk3Var2": 0,
            "perk3Var1": 127,
            "damageSelfMitigated": 7987,
            "magicalDamageTaken": 9436,
            "perk0Var2": 571,
            "firstInhibitorKill": false,
            "trueDamageTaken": 674,
            "assists": 1,
            "perk4Var2": 0,
            "goldSpent": 7050,
            "trueDamageDealt": 3674,
            "participantId": 4,
            "physicalDamageDealt": 57791,
            "sightWardsBoughtInGame": 0,
            "totalDamageDealtToChampions": 8934,
            "physicalDamageTaken": 11347,
            "totalPlayerScore": 0,
            "win": false,
            "objectivePlayerScore": 0,
            "totalDamageDealt": 73110,
            "neutralMinionsKilledEnemyJungle": 0,
            "deaths": 10,
            "wardsPlaced": 9,
            "perkPrimaryStyle": 8000,
            "perkSubStyle": 8100,
            "turretKills": 0,
            "firstBloodKill": false,
            "trueDamageDealtToChampions": 404,
            "goldEarned": 7188,
            "killingSprees": 0,
            "unrealKills": 0,
            "firstTowerAssist": false,
            "firstTowerKill": false,
            "champLevel": 11,
            "doubleKills": 0,
            "inhibitorKills": 0,
            "firstInhibitorAssist": false,
            "perk0Var1": 1175,
            "combatPlayerScore": 0,
            "perk0Var3": 603,
            "visionWardsBoughtInGame": 0,
            "pentaKills": 0,
            "totalHeal": 1832,
            "totalMinionsKilled": 131,
            "timeCCingOthers": 19
        },
        "spell1Id": 7,
        "participantId": 4,
        "highestAchievedSeasonTier": "GOLD",
        "spell2Id": 4,
        "teamId": 100,
        "timeline": {
            "lane": "BOTTOM",
            "participantId": 4,
            "csDiffPerMinDeltas": {
                "0-10": -0.95,
                "10-20": -2.55
            },
            "goldPerMinDeltas": {
                "0-10": 208.9,
                "10-20": 249.3
            },
            "xpDiffPerMinDeltas": {
                "0-10": 4.499999999999986,
                "10-20": -214.15000000000003
            },
            "creepsPerMinDeltas": {
                "0-10": 5.5,
                "10-20": 4.8
            },
            "xpPerMinDeltas": {
                "0-10": 271.2,
                "10-20": 320.6
            },
            "role": "DUO_CARRY",
            "damageTakenDiffPerMinDeltas": {
                "0-10": 26.5,
                "10-20": 118.80000000000001
            },
            "damageTakenPerMinDeltas": {
                "0-10": 350.5,
                "10-20": 744.6
            }
        },
        "championId": 110
    },
    {
        "stats": {
            "neutralMinionsKilledTeamJungle": 0,
            "visionScore": 8,
            "magicDamageDealtToChampions": 4909,
            "largestMultiKill": 1,
            "totalTimeCrowdControlDealt": 31,
            "longestTimeSpentLiving": 687,
            "perk1Var1": 15,
            "perk1Var3": 0,
            "perk1Var2": 0,
            "tripleKills": 0,
            "perk5": 8143,
            "perk4": 8135,
            "playerScore9": 0,
            "playerScore8": 0,
            "kills": 2,
            "playerScore1": 0,
            "playerScore0": 0,
            "playerScore3": 0,
            "playerScore2": 0,
            "playerScore5": 0,
            "playerScore4": 0,
            "playerScore7": 0,
            "playerScore6": 0,
            "perk5Var1": 197,
            "perk5Var3": 0,
            "perk5Var2": 0,
            "totalScoreRank": 0,
            "neutralMinionsKilled": 0,
            "damageDealtToTurrets": 0,
            "physicalDamageDealtToChampions": 133,
            "damageDealtToObjectives": 0,
            "perk2Var2": 0,
            "perk2Var3": 0,
            "totalUnitsHealed": 1,
            "perk2Var1": 0,
            "perk4Var1": 2,
            "totalDamageTaken": 15731,
            "perk4Var3": 0,
            "wardsKilled": 3,
            "largestCriticalStrike": 0,
            "largestKillingSpree": 0,
            "quadraKills": 0,
            "magicDamageDealt": 33106,
            "firstBloodAssist": false,
            "item2": 3165,
            "item3": 3108,
            "item0": 1056,
            "item1": 2420,
            "item6": 3340,
            "item4": 3020,
            "item5": 1052,
            "perk1": 8243,
            "perk0": 8229,
            "perk3": 8236,
            "perk2": 8210,
            "perk3Var3": 0,
            "perk3Var2": 0,
            "perk3Var1": 24,
            "damageSelfMitigated": 4768,
            "magicalDamageTaken": 8768,
            "perk0Var2": 0,
            "firstInhibitorKill": false,
            "trueDamageTaken": 1158,
            "assists": 2,
            "perk4Var2": 0,
            "goldSpent": 7835,
            "trueDamageDealt": 22018,
            "participantId": 5,
            "physicalDamageDealt": 12404,
            "sightWardsBoughtInGame": 0,
            "totalDamageDealtToChampions": 7624,
            "physicalDamageTaken": 5803,
            "totalPlayerScore": 0,
            "win": false,
            "objectivePlayerScore": 0,
            "totalDamageDealt": 67528,
            "neutralMinionsKilledEnemyJungle": 0,
            "deaths": 7,
            "wardsPlaced": 5,
            "perkPrimaryStyle": 8200,
            "perkSubStyle": 8100,
            "turretKills": 0,
            "firstBloodKill": false,
            "trueDamageDealtToChampions": 2581,
            "goldEarned": 7499,
            "killingSprees": 0,
            "unrealKills": 0,
            "firstTowerAssist": false,
            "firstTowerKill": false,
            "champLevel": 13,
            "doubleKills": 0,
            "inhibitorKills": 0,
            "firstInhibitorAssist": false,
            "perk0Var1": 784,
            "combatPlayerScore": 0,
            "perk0Var3": 0,
            "visionWardsBoughtInGame": 0,
            "pentaKills": 0,
            "totalHeal": 1295,
            "totalMinionsKilled": 126,
            "timeCCingOthers": 7
        },
        "spell1Id": 14,
        "participantId": 5,
        "highestAchievedSeasonTier": "SILVER",
        "spell2Id": 4,
        "teamId": 100,
        "timeline": {
            "lane": "MIDDLE",
            "participantId": 5,
            "csDiffPerMinDeltas": {
                "0-10": -3.0999999999999996,
                "10-20": -3.6
            },
            "goldPerMinDeltas": {
                "0-10": 181.8,
                "10-20": 270.9
            },
            "xpDiffPerMinDeltas": {
                "0-10": -58.29999999999998,
                "10-20": -323.69999999999993
            },
            "creepsPerMinDeltas": {
                "0-10": 3.7,
                "10-20": 4.4
            },
            "xpPerMinDeltas": {
                "0-10": 389.1,
                "10-20": 330.1
            },
            "role": "SOLO",
            "damageTakenDiffPerMinDeltas": {
                "0-10": 127.9,
                "10-20": 331.20000000000005
            },
            "damageTakenPerMinDeltas": {
                "0-10": 226.60000000000002,
                "10-20": 665.6
            }
        },
        "championId": 103
    },
    {
        "stats": {
            "neutralMinionsKilledTeamJungle": 1,
            "visionScore": 14,
            "magicDamageDealtToChampions": 15100,
            "largestMultiKill": 1,
            "totalTimeCrowdControlDealt": 619,
            "longestTimeSpentLiving": 538,
            "perk1Var1": 1405,
            "perk1Var3": 0,
            "perk1Var2": 0,
            "tripleKills": 0,
            "perk5": 8304,
            "perk4": 8347,
            "playerScore9": 0,
            "playerScore8": 0,
            "kills": 3,
            "playerScore1": 0,
            "playerScore0": 0,
            "playerScore3": 0,
            "playerScore2": 0,
            "playerScore5": 0,
            "playerScore4": 0,
            "playerScore7": 0,
            "playerScore6": 0,
            "perk5Var1": 10,
            "perk5Var3": 0,
            "perk5Var2": 0,
            "totalScoreRank": 0,
            "neutralMinionsKilled": 16,
            "damageDealtToTurrets": 7670,
            "physicalDamageDealtToChampions": 1876,
            "damageDealtToObjectives": 7670,
            "perk2Var2": 0,
            "perk2Var3": 0,
            "totalUnitsHealed": 1,
            "perk2Var1": 1044,
            "perk4Var1": 0,
            "totalDamageTaken": 14551,
            "perk4Var3": 0,
            "wardsKilled": 2,
            "largestCriticalStrike": 0,
            "largestKillingSpree": 2,
            "quadraKills": 0,
            "magicDamageDealt": 120610,
            "firstBloodAssist": false,
            "item2": 3115,
            "item3": 3151,
            "item0": 1056,
            "item1": 2031,
            "item6": 3340,
            "item4": 3020,
            "item5": 3285,
            "perk1": 8226,
            "perk0": 8214,
            "perk3": 8236,
            "perk2": 8233,
            "perk3Var3": 0,
            "perk3Var2": 0,
            "perk3Var1": 24,
            "damageSelfMitigated": 4252,
            "magicalDamageTaken": 9743,
            "perk0Var2": 0,
            "firstInhibitorKill": false,
            "trueDamageTaken": 841,
            "assists": 4,
            "perk4Var2": 0,
            "goldSpent": 10800,
            "trueDamageDealt": 7096,
            "participantId": 6,
            "physicalDamageDealt": 43436,
            "sightWardsBoughtInGame": 0,
            "totalDamageDealtToChampions": 18092,
            "physicalDamageTaken": 3965,
            "totalPlayerScore": 0,
            "win": true,
            "objectivePlayerScore": 0,
            "totalDamageDealt": 171143,
            "neutralMinionsKilledEnemyJungle": 8,
            "deaths": 5,
            "wardsPlaced": 9,
            "perkPrimaryStyle": 8200,
            "perkSubStyle": 8300,
            "turretKills": 3,
            "firstBloodKill": false,
            "trueDamageDealtToChampions": 1115,
            "goldEarned": 12572,
            "killingSprees": 1,
            "unrealKills": 0,
            "firstTowerAssist": false,
            "firstTowerKill": false,
            "champLevel": 16,
            "doubleKills": 0,
            "inhibitorKills": 1,
            "firstInhibitorAssist": false,
            "perk0Var1": 1337,
            "combatPlayerScore": 0,
            "perk0Var3": 0,
            "visionWardsBoughtInGame": 0,
            "pentaKills": 0,
            "totalHeal": 641,
            "totalMinionsKilled": 243,
            "timeCCingOthers": 29
        },
        "spell1Id": 14,
        "participantId": 6,
        "highestAchievedSeasonTier": "GOLD",
        "spell2Id": 12,
        "teamId": 200,
        "timeline": {
            "lane": "TOP",
            "participantId": 6,
            "csDiffPerMinDeltas": {
                "0-10": 0.4000000000000008,
                "10-20": 0.1999999999999993
            },
            "goldPerMinDeltas": {
                "0-10": 250.60000000000002,
                "10-20": 430.7
            },
            "xpDiffPerMinDeltas": {
                "0-10": 19.19999999999999,
                "10-20": -94.70000000000005
            },
            "creepsPerMinDeltas": {
                "0-10": 7.6000000000000005,
                "10-20": 8.6
            },
            "xpPerMinDeltas": {
                "0-10": 439.9,
                "10-20": 569.5999999999999
            },
            "role": "SOLO",
            "damageTakenDiffPerMinDeltas": {
                "0-10": -15.899999999999991,
                "10-20": -232.40000000000003
            },
            "damageTakenPerMinDeltas": {
                "0-10": 287.4,
                "10-20": 640.8
            }
        },
        "championId": 17
    },
    {
        "stats": {
            "neutralMinionsKilledTeamJungle": 0,
            "visionScore": 9,
            "magicDamageDealtToChampions": 23053,
            "largestMultiKill": 2,
            "totalTimeCrowdControlDealt": 145,
            "longestTimeSpentLiving": 1288,
            "perk1Var1": 1509,
            "perk1Var3": 0,
            "perk1Var2": 0,
            "tripleKills": 0,
            "perk5": 8138,
            "perk4": 8126,
            "playerScore9": 0,
            "playerScore8": 0,
            "kills": 15,
            "playerScore1": 0,
            "playerScore0": 0,
            "playerScore3": 0,
            "playerScore2": 0,
            "playerScore5": 0,
            "playerScore4": 0,
            "playerScore7": 0,
            "playerScore6": 0,
            "perk5Var1": 30,
            "perk5Var3": 0,
            "perk5Var2": 0,
            "totalScoreRank": 0,
            "neutralMinionsKilled": 0,
            "damageDealtToTurrets": 5297,
            "physicalDamageDealtToChampions": 1600,
            "damageDealtToObjectives": 7104,
            "perk2Var2": 0,
            "perk2Var3": 0,
            "totalUnitsHealed": 1,
            "perk2Var1": 0,
            "perk4Var1": 334,
            "totalDamageTaken": 9840,
            "perk4Var3": 0,
            "wardsKilled": 2,
            "largestCriticalStrike": 0,
            "largestKillingSpree": 8,
            "quadraKills": 0,
            "magicDamageDealt": 81737,
            "firstBloodAssist": false,
            "item2": 3100,
            "item3": 3020,
            "item0": 3165,
            "item1": 1056,
            "item6": 3363,
            "item4": 1058,
            "item5": 1026,
            "perk1": 8226,
            "perk0": 8229,
            "perk3": 8237,
            "perk2": 8210,
            "perk3Var3": 0,
            "perk3Var2": 0,
            "perk3Var1": 429,
            "damageSelfMitigated": 2594,
            "magicalDamageTaken": 4684,
            "perk0Var2": 0,
            "firstInhibitorKill": false,
            "trueDamageTaken": 868,
            "assists": 5,
            "perk4Var2": 0,
            "goldSpent": 9925,
            "trueDamageDealt": 13105,
            "participantId": 7,
            "physicalDamageDealt": 18643,
            "sightWardsBoughtInGame": 0,
            "totalDamageDealtToChampions": 27344,
            "physicalDamageTaken": 4286,
            "totalPlayerScore": 0,
            "win": true,
            "objectivePlayerScore": 0,
            "totalDamageDealt": 113485,
            "neutralMinionsKilledEnemyJungle": 0,
            "deaths": 1,
            "wardsPlaced": 9,
            "perkPrimaryStyle": 8200,
            "perkSubStyle": 8100,
            "turretKills": 1,
            "firstBloodKill": false,
            "trueDamageDealtToChampions": 2690,
            "goldEarned": 12228,
            "killingSprees": 2,
            "unrealKills": 0,
            "firstTowerAssist": false,
            "firstTowerKill": false,
            "champLevel": 15,
            "doubleKills": 2,
            "inhibitorKills": 0,
            "firstInhibitorAssist": false,
            "perk0Var1": 1188,
            "combatPlayerScore": 0,
            "perk0Var3": 0,
            "visionWardsBoughtInGame": 1,
            "pentaKills": 0,
            "totalHeal": 1181,
            "totalMinionsKilled": 157,
            "timeCCingOthers": 22
        },
        "spell1Id": 14,
        "participantId": 7,
        "highestAchievedSeasonTier": "UNRANKED",
        "spell2Id": 4,
        "teamId": 200,
        "timeline": {
            "lane": "MIDDLE",
            "participantId": 7,
            "csDiffPerMinDeltas": {
                "0-10": 3.0999999999999996,
                "10-20": 3.6
            },
            "goldPerMinDeltas": {
                "0-10": 253.89999999999998,
                "10-20": 556.1
            },
            "xpDiffPerMinDeltas": {
                "0-10": 58.29999999999998,
                "10-20": 323.69999999999993
            },
            "creepsPerMinDeltas": {
                "0-10": 6.8,
                "10-20": 8
            },
            "xpPerMinDeltas": {
                "0-10": 447.4,
                "10-20": 653.8
            },
            "role": "SOLO",
            "damageTakenDiffPerMinDeltas": {
                "0-10": -127.9,
                "10-20": -331.20000000000005
            },
            "damageTakenPerMinDeltas": {
                "0-10": 98.7,
                "10-20": 334.4
            }
        },
        "championId": 142
    },
        {
        "stats": {
            "neutralMinionsKilledTeamJungle": 0,
            "visionScore": 83,
            "magicDamageDealtToChampions": 6033,
            "largestMultiKill": 2,
            "totalTimeCrowdControlDealt": 92,
            "longestTimeSpentLiving": 0,
            "perk1Var1": 1478,
            "perk1Var3": 0,
            "perk1Var2": 0,
            "tripleKills": 0,
            "perk5": 8134,
            "perk4": 8136,
            "playerScore9": 0,
            "playerScore8": 0,
            "kills": 4,
            "playerScore1": 0,
            "playerScore0": 0,
            "playerScore3": 0,
            "playerScore2": 0,
            "playerScore5": 0,
            "playerScore4": 0,
            "playerScore7": 0,
            "playerScore6": 0,
            "perk5Var1": 5,
            "perk5Var3": 0,
            "perk5Var2": 0,
            "totalScoreRank": 0,
            "neutralMinionsKilled": 0,
            "damageDealtToTurrets": 3125,
            "physicalDamageDealtToChampions": 544,
            "damageDealtToObjectives": 3641,
            "perk2Var2": 0,
            "perk2Var3": 0,
            "totalUnitsHealed": 4,
            "perk2Var1": 40,
            "perk4Var1": 15,
            "totalDamageTaken": 15025,
            "perk4Var3": 0,
            "wardsKilled": 13,
            "largestCriticalStrike": 0,
            "largestKillingSpree": 4,
            "quadraKills": 0,
            "magicDamageDealt": 9301,
            "firstBloodAssist": false,
            "item2": 2049,
            "item3": 3109,
            "item0": 3190,
            "item1": 2055,
            "item6": 3364,
            "item4": 3097,
            "item5": 3009,
            "perk1": 8446,
            "perk0": 8465,
            "perk3": 8451,
            "perk2": 8430,
            "perk3Var3": 0,
            "perk3Var2": 0,
            "perk3Var1": 123,
            "damageSelfMitigated": 19578,
            "magicalDamageTaken": 7167,
            "perk0Var2": 0,
            "firstInhibitorKill": false,
            "trueDamageTaken": 719,
            "assists": 17,
            "perk4Var2": 0,
            "goldSpent": 7700,
            "trueDamageDealt": 5098,
            "participantId": 8,
            "physicalDamageDealt": 6902,
            "sightWardsBoughtInGame": 0,
            "totalDamageDealtToChampions": 6578,
            "physicalDamageTaken": 7139,
            "totalPlayerScore": 0,
            "win": true,
            "objectivePlayerScore": 0,
            "totalDamageDealt": 21302,
            "neutralMinionsKilledEnemyJungle": 0,
            "deaths": 0,
            "wardsPlaced": 42,
            "perkPrimaryStyle": 8400,
            "perkSubStyle": 8100,
            "turretKills": 1,
            "firstBloodKill": false,
            "trueDamageDealtToChampions": 0,
            "goldEarned": 9690,
            "killingSprees": 1,
            "unrealKills": 0,
            "firstTowerAssist": true,
            "firstTowerKill": false,
            "champLevel": 14,
            "doubleKills": 1,
            "inhibitorKills": 0,
            "firstInhibitorAssist": false,
            "perk0Var1": 2110,
            "combatPlayerScore": 0,
            "perk0Var3": 0,
            "visionWardsBoughtInGame": 8,
            "pentaKills": 0,
            "totalHeal": 6010,
            "totalMinionsKilled": 43,
            "timeCCingOthers": 13
        },
        "spell1Id": 4,
        "participantId": 8,
        "highestAchievedSeasonTier": "BRONZE",
        "spell2Id": 3,
        "teamId": 200,
        "timeline": {
            "lane": "BOTTOM",
            "participantId": 8,
            "csDiffPerMinDeltas": {
                "0-10": 0.95,
                "10-20": 2.55
            },
            "goldPerMinDeltas": {
                "0-10": 137,
                "10-20": 433.2
            },
            "xpDiffPerMinDeltas": {
                "0-10": -4.499999999999986,
                "10-20": 214.15000000000003
            },
            "creepsPerMinDeltas": {
                "0-10": 1.1,
                "10-20": 2
            },
            "xpPerMinDeltas": {
                "0-10": 239.39999999999998,
                "10-20": 462.8
            },
            "role": "DUO_SUPPORT",
            "damageTakenDiffPerMinDeltas": {
                "0-10": -26.5,
                "10-20": -118.80000000000001
            },
            "damageTakenPerMinDeltas": {
                "0-10": 248.2,
                "10-20": 471.6
            }
        },
        "championId": 223
    },
    {
        "stats": {
            "neutralMinionsKilledTeamJungle": 114,
            "visionScore": 17,
            "magicDamageDealtToChampions": 3355,
            "largestMultiKill": 1,
            "totalTimeCrowdControlDealt": 1167,
            "longestTimeSpentLiving": 881,
            "perk1Var1": 1164,
            "perk1Var3": 0,
            "perk1Var2": 0,
            "tripleKills": 0,
            "perk5": 8105,
            "perk4": 8143,
            "playerScore9": 0,
            "playerScore8": 0,
            "kills": 5,
            "playerScore1": 0,
            "playerScore0": 0,
            "playerScore3": 0,
            "playerScore2": 0,
            "playerScore5": 0,
            "playerScore4": 0,
            "playerScore7": 0,
            "playerScore6": 0,
            "perk5Var1": 4,
            "perk5Var3": 0,
            "perk5Var2": 0,
            "totalScoreRank": 0,
            "neutralMinionsKilled": 175,
            "damageDealtToTurrets": 3661,
            "physicalDamageDealtToChampions": 6513,
            "damageDealtToObjectives": 15662,
            "perk2Var2": 34,
            "perk2Var3": 0,
            "totalUnitsHealed": 1,
            "perk2Var1": 14,
            "perk4Var1": 339,
            "totalDamageTaken": 24901,
            "perk4Var3": 0,
            "wardsKilled": 1,
            "largestCriticalStrike": 0,
            "largestKillingSpree": 3,
            "quadraKills": 0,
            "magicDamageDealt": 77036,
            "firstBloodAssist": false,
            "item2": 3111,
            "item3": 3022,
            "item0": 1419,
            "item1": 3153,
            "item6": 3364,
            "item4": 0,
            "item5": 2031,
            "perk1": 9111,
            "perk0": 8005,
            "perk3": 8014,
            "perk2": 9103,
            "perk3Var3": 0,
            "perk3Var2": 0,
            "perk3Var1": 407,
            "damageSelfMitigated": 16800,
            "magicalDamageTaken": 6436,
            "perk0Var2": 681,
            "firstInhibitorKill": false,
            "trueDamageTaken": 523,
            "assists": 8,
            "perk4Var2": 0,
            "goldSpent": 10450,
            "trueDamageDealt": 11607,
            "participantId": 9,
            "physicalDamageDealt": 102245,
            "sightWardsBoughtInGame": 0,
            "totalDamageDealtToChampions": 10412,
            "physicalDamageTaken": 17941,
            "totalPlayerScore": 0,
            "win": true,
            "objectivePlayerScore": 0,
            "totalDamageDealt": 190889,
            "neutralMinionsKilledEnemyJungle": 18,
            "deaths": 1,
            "wardsPlaced": 5,
            "perkPrimaryStyle": 8000,
            "perkSubStyle": 8100,
            "turretKills": 3,
            "firstBloodKill": true,
            "trueDamageDealtToChampions": 544,
            "goldEarned": 12767,
            "killingSprees": 2,
            "unrealKills": 0,
            "firstTowerAssist": false,
            "firstTowerKill": false,
            "champLevel": 16,
            "doubleKills": 0,
            "inhibitorKills": 0,
            "firstInhibitorAssist": true,
            "perk0Var1": 859,
            "combatPlayerScore": 0,
            "perk0Var3": 178,
            "visionWardsBoughtInGame": 1,
            "pentaKills": 0,
            "totalHeal": 9841,
            "totalMinionsKilled": 30,
            "timeCCingOthers": 5
        },
        "spell1Id": 11,
        "participantId": 9,
        "highestAchievedSeasonTier": "DIAMOND",
        "spell2Id": 4,
        "teamId": 200,
        "timeline": {
            "lane": "JUNGLE",
            "participantId": 9,
            "csDiffPerMinDeltas": {
                "0-10": -1.4,
                "10-20": -2.3
            },
            "goldPerMinDeltas": {
                "0-10": 282.4,
                "10-20": 453.20000000000005
            },
            "xpDiffPerMinDeltas": {
                "0-10": -20,
                "10-20": 259.90000000000003
            },
            "creepsPerMinDeltas": {
                "0-10": 0,
                "10-20": 1.7
            },
            "xpPerMinDeltas": {
                "0-10": 315.1,
                "10-20": 636.1
            },
            "role": "NONE",
            "damageTakenDiffPerMinDeltas": {
                "0-10": 79.30000000000001,
                "10-20": -20.5
            },
            "damageTakenPerMinDeltas": {
                "0-10": 565.2,
                "10-20": 809.8
            }
        },
        "championId": 102
    },
    {
        "stats": {
            "neutralMinionsKilledTeamJungle": 0,
            "visionScore": 18,
            "magicDamageDealtToChampions": 1893,
            "largestMultiKill": 3,
            "totalTimeCrowdControlDealt": 156,
            "longestTimeSpentLiving": 745,
            "perk1Var1": 15,
            "perk1Var3": 0,
            "perk1Var2": 0,
            "tripleKills": 1,
            "perk5": 8014,
            "perk4": 9105,
            "playerScore9": 0,
            "playerScore8": 0,
            "kills": 10,
            "playerScore1": 0,
            "playerScore0": 0,
            "playerScore3": 0,
            "playerScore2": 0,
            "playerScore5": 0,
            "playerScore4": 0,
            "playerScore7": 0,
            "playerScore6": 0,
            "perk5Var1": 584,
            "perk5Var3": 0,
            "perk5Var2": 0,
            "totalScoreRank": 0,
            "neutralMinionsKilled": 12,
            "damageDealtToTurrets": 10005,
            "physicalDamageDealtToChampions": 22763,
            "damageDealtToObjectives": 13972,
            "perk2Var2": 0,
            "perk2Var3": 0,
            "totalUnitsHealed": 2,
            "perk2Var1": 15,
            "perk4Var1": 16,
            "totalDamageTaken": 13572,
            "perk4Var3": 0,
            "wardsKilled": 2,
            "largestCriticalStrike": 745,
            "largestKillingSpree": 7,
            "quadraKills": 0,
            "magicDamageDealt": 4026,
            "firstBloodAssist": false,
            "item2": 3072,
            "item3": 3006,
            "item0": 3144,
            "item1": 2033,
            "item6": 3363,
            "item4": 1042,
            "item5": 3812,
            "perk1": 8243,
            "perk0": 8214,
            "perk3": 8237,
            "perk2": 8234,
            "perk3Var3": 0,
            "perk3Var2": 0,
            "perk3Var1": 761,
            "damageSelfMitigated": 12138,
            "magicalDamageTaken": 4500,
            "perk0Var2": 121,
            "firstInhibitorKill": true,
            "trueDamageTaken": 3049,
            "assists": 10,
            "perk4Var2": 17,
            "goldSpent": 10600,
            "trueDamageDealt": 2118,
            "participantId": 10,
            "physicalDamageDealt": 121129,
            "sightWardsBoughtInGame": 0,
            "totalDamageDealtToChampions": 24852,
            "physicalDamageTaken": 6021,
            "totalPlayerScore": 0,
            "win": true,
            "objectivePlayerScore": 0,
            "totalDamageDealt": 127274,
            "neutralMinionsKilledEnemyJungle": 4,
            "deaths": 2,
            "wardsPlaced": 11,
            "perkPrimaryStyle": 8200,
            "perkSubStyle": 8000,
            "turretKills": 3,
            "firstBloodKill": false,
            "trueDamageDealtToChampions": 196,
            "goldEarned": 13411,
            "killingSprees": 2,
            "unrealKills": 0,
            "firstTowerAssist": false,
            "firstTowerKill": true,
            "champLevel": 14,
            "doubleKills": 2,
            "inhibitorKills": 1,
            "firstInhibitorAssist": false,
            "perk0Var1": 1312,
            "combatPlayerScore": 0,
            "perk0Var3": 0,
            "visionWardsBoughtInGame": 0,
            "pentaKills": 0,
            "totalHeal": 4770,
            "totalMinionsKilled": 211,
            "timeCCingOthers": 7
        },
        "spell1Id": 4,
        "participantId": 10,
        "highestAchievedSeasonTier": "PLATINUM",
        "spell2Id": 7,
        "teamId": 200,
        "timeline": {
            "lane": "BOTTOM",
            "participantId": 10,
            "csDiffPerMinDeltas": {
                "0-10": 0.95,
                "10-20": 2.55
            },
            "goldPerMinDeltas": {
                "0-10": 224.8,
                "10-20": 560.9000000000001
            },
            "xpDiffPerMinDeltas": {
                "0-10": -4.499999999999986,
                "10-20": 214.15000000000003
            },
            "creepsPerMinDeltas": {
                "0-10": 6.4,
                "10-20": 8.5
            },
            "xpPerMinDeltas": {
                "0-10": 273.4,
                "10-20": 551
            },
            "role": "DUO_CARRY",
            "damageTakenDiffPerMinDeltas": {
                "0-10": -26.5,
                "10-20": -118.80000000000001
            },
            "damageTakenPerMinDeltas": {
                "0-10": 243.2,
                "10-20": 557.9
            }
        },
        "championId": 21
    }
],
    "gameDuration": 1675,
    "gameCreation": 1514102232876
};