module.exports.matchInfo = {
    "seasonId": 9,
    "queueId": 450,
    "gameId": 2678233070,
    "participantIdentities": [
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "Violet2017",
                "matchHistoryUri": "/v1/stats/player_history/NA1/240990396",
                "platformId": "NA1",
                "currentAccountId": 240990396,
                "profileIcon": 3008,
                "summonerId": 89450885,
                "accountId": 240990396
            },
            "participantId": 1
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "Anduiin",
                "matchHistoryUri": "/v1/stats/player_history/NA1/229654783",
                "platformId": "NA1",
                "currentAccountId": 229654783,
                "profileIcon": 3158,
                "summonerId": 69341115,
                "accountId": 229654783
            },
            "participantId": 2
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "adorable wasabi",
                "matchHistoryUri": "/v1/stats/player_history/NA1/232157132",
                "platformId": "NA1",
                "currentAccountId": 232157132,
                "profileIcon": 3156,
                "summonerId": 73721980,
                "accountId": 232157132
            },
            "participantId": 3
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "meCry During Sex",
                "matchHistoryUri": "/v1/stats/player_history/NA1/50859384",
                "platformId": "NA1",
                "currentAccountId": 50859384,
                "profileIcon": 3186,
                "summonerId": 36454312,
                "accountId": 50859384
            },
            "participantId": 4
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "DeadCatBounce14",
                "matchHistoryUri": "/v1/stats/player_history/NA/41324371",
                "platformId": "NA",
                "currentAccountId": 41324371,
                "profileIcon": 2,
                "summonerId": 26700862,
                "accountId": 41324371
            },
            "participantId": 5
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "Air King",
                "matchHistoryUri": "/v1/stats/player_history/NA/32176212",
                "platformId": "NA",
                "currentAccountId": 32176212,
                "profileIcon": 508,
                "summonerId": 19482328,
                "accountId": 32176212
            },
            "participantId": 6
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "SkaterSkillz",
                "matchHistoryUri": "/v1/stats/player_history/NA1/215680287",
                "platformId": "NA1",
                "currentAccountId": 215680287,
                "profileIcon": 665,
                "summonerId": 53119963,
                "accountId": 215680287
            },
            "participantId": 7
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "Mooooye",
                "matchHistoryUri": "/v1/stats/player_history/NA1/232108616",
                "platformId": "NA1",
                "currentAccountId": 232108616,
                "profileIcon": 1430,
                "summonerId": 73740922,
                "accountId": 232108616
            },
            "participantId": 8
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "88888888888888",
                "matchHistoryUri": "/v1/stats/player_history/NA1/42702115",
                "platformId": "NA1",
                "currentAccountId": 42702115,
                "profileIcon": 3186,
                "summonerId": 28346043,
                "accountId": 42702115
            },
            "participantId": 9
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "Mark and Sweep",
                "matchHistoryUri": "/v1/stats/player_history/NA1/208867949",
                "platformId": "NA1",
                "currentAccountId": 208867949,
                "profileIcon": 937,
                "summonerId": 45807928,
                "accountId": 208867949
            },
            "participantId": 10
        }
    ],
    "gameVersion": "7.24.212.5337",
    "platformId": "NA1",
    "gameMode": "ARAM",
    "mapId": 12,
    "gameType": "MATCHED_GAME",
    "teams": [
        {
            "firstDragon": false,
            "bans": [],
            "firstInhibitor": false,
            "win": "Fail",
            "firstRiftHerald": false,
            "firstBaron": false,
            "baronKills": 0,
            "riftHeraldKills": 0,
            "firstBlood": false,
            "teamId": 100,
            "firstTower": false,
            "vilemawKills": 0,
            "inhibitorKills": 0,
            "towerKills": 1,
            "dominionVictoryScore": 0,
            "dragonKills": 0
        },
        {
            "firstDragon": false,
            "bans": [],
            "firstInhibitor": true,
            "win": "Win",
            "firstRiftHerald": false,
            "firstBaron": false,
            "baronKills": 0,
            "riftHeraldKills": 0,
            "firstBlood": true,
            "teamId": 200,
            "firstTower": true,
            "vilemawKills": 0,
            "inhibitorKills": 1,
            "towerKills": 4,
            "dominionVictoryScore": 0,
            "dragonKills": 0
        }
    ],
    "participants": [
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 6158,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 101,
                "longestTimeSpentLiving": 300,
                "perk1Var1": 1332,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8120,
                "perk4": 8143,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 2,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 5,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 3,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "damageDealtToTurrets": 1072,
                "physicalDamageDealtToChampions": 452,
                "damageDealtToObjectives": 1072,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 11,
                "perk2Var1": 15,
                "perk4Var1": 2,
                "totalDamageTaken": 14397,
                "perk4Var3": 0,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 0,
                "quadraKills": 0,
                "magicDamageDealt": 12500,
                "item2": 3504,
                "item3": 3117,
                "item0": 3107,
                "item1": 3222,
                "item6": 2052,
                "item4": 3105,
                "item5": 0,
                "perk1": 8226,
                "perk0": 8214,
                "perk3": 8237,
                "perk2": 8234,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 577,
                "damageSelfMitigated": 9317,
                "magicalDamageTaken": 4632,
                "perk0Var2": 1576,
                "firstInhibitorKill": false,
                "trueDamageTaken": 30,
                "assists": 20,
                "perk4Var2": 0,
                "goldSpent": 8700,
                "trueDamageDealt": 1189,
                "participantId": 1,
                "physicalDamageDealt": 2273,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 7050,
                "physicalDamageTaken": 9735,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 15963,
                "deaths": 7,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8100,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 439,
                "goldEarned": 10141,
                "killingSprees": 0,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 16,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "firstInhibitorAssist": false,
                "perk0Var1": 1061,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 4084,
                "totalMinionsKilled": 6,
                "timeCCingOthers": 30
            },
            "spell1Id": 7,
            "participantId": 1,
            "highestAchievedSeasonTier": "UNRANKED",
            "spell2Id": 32,
            "teamId": 100,
            "timeline": {
                "lane": "MIDDLE",
                "participantId": 1,
                "csDiffPerMinDeltas": {
                    "0-10": -0.3999999999999998
                },
                "goldPerMinDeltas": {
                    "0-10": 415.5
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -25.219999999999942
                },
                "creepsPerMinDeltas": {
                    "0-10": 0.5
                },
                "xpPerMinDeltas": {
                    "0-10": 685.3
                },
                "role": "NONE",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 150.8
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 445.79999999999995
                }
            },
            "championId": 40
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 1705,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 245,
                "longestTimeSpentLiving": 208,
                "perk1Var1": 1583,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8135,
                "perk4": 8139,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 8,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 5,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "damageDealtToTurrets": 970,
                "physicalDamageDealtToChampions": 17487,
                "damageDealtToObjectives": 970,
                "perk2Var2": 9,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 11,
                "perk4Var1": 837,
                "totalDamageTaken": 25062,
                "perk4Var3": 0,
                "largestCriticalStrike": 384,
                "largestKillingSpree": 0,
                "quadraKills": 0,
                "magicDamageDealt": 5632,
                "item2": 0,
                "item3": 3046,
                "item0": 3031,
                "item1": 3143,
                "item6": 2052,
                "item4": 3047,
                "item5": 3155,
                "perk1": 9111,
                "perk0": 8005,
                "perk3": 8014,
                "perk2": 9104,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 582,
                "damageSelfMitigated": 36364,
                "magicalDamageTaken": 10146,
                "perk0Var2": 589,
                "firstInhibitorKill": false,
                "trueDamageTaken": 25,
                "assists": 14,
                "perk4Var2": 0,
                "goldSpent": 12400,
                "trueDamageDealt": 906,
                "participantId": 2,
                "physicalDamageDealt": 67405,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 20099,
                "physicalDamageTaken": 14891,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 73944,
                "deaths": 9,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 906,
                "goldEarned": 12176,
                "killingSprees": 0,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 16,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "firstInhibitorAssist": false,
                "perk0Var1": 945,
                "combatPlayerScore": 0,
                "perk0Var3": 356,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 4423,
                "totalMinionsKilled": 53,
                "timeCCingOthers": 53
            },
            "spell1Id": 14,
            "participantId": 2,
            "highestAchievedSeasonTier": "GOLD",
            "spell2Id": 4,
            "teamId": 100,
            "timeline": {
                "lane": "MIDDLE",
                "participantId": 2,
                "csDiffPerMinDeltas": {
                    "0-10": -0.3999999999999998
                },
                "goldPerMinDeltas": {
                    "0-10": 500.1
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -25.219999999999942
                },
                "creepsPerMinDeltas": {
                    "0-10": 2.5
                },
                "xpPerMinDeltas": {
                    "0-10": 594.2
                },
                "role": "NONE",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 150.8
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 907.7
                }
            },
            "championId": 157
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 1652,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 67,
                "longestTimeSpentLiving": 156,
                "perk1Var1": 25,
                "perk1Var3": 0,
                "perk1Var2": 111,
                "tripleKills": 0,
                "perk5": 8138,
                "perk4": 8139,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 4,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 18,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "damageDealtToTurrets": 557,
                "physicalDamageDealtToChampions": 8365,
                "damageDealtToObjectives": 557,
                "perk2Var2": 56,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 13,
                "perk4Var1": 450,
                "totalDamageTaken": 19070,
                "perk4Var3": 0,
                "largestCriticalStrike": 569,
                "largestKillingSpree": 0,
                "quadraKills": 0,
                "magicDamageDealt": 5776,
                "item2": 3082,
                "item3": 3087,
                "item0": 3153,
                "item1": 1028,
                "item6": 2052,
                "item4": 3111,
                "item5": 1029,
                "perk1": 9101,
                "perk0": 8005,
                "perk3": 8014,
                "perk2": 9104,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 278,
                "damageSelfMitigated": 17642,
                "magicalDamageTaken": 7273,
                "perk0Var2": 310,
                "firstInhibitorKill": false,
                "trueDamageTaken": 35,
                "assists": 12,
                "perk4Var2": 0,
                "goldSpent": 9000,
                "trueDamageDealt": 1129,
                "participantId": 3,
                "physicalDamageDealt": 31460,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 10649,
                "physicalDamageTaken": 11762,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 38365,
                "deaths": 12,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 632,
                "goldEarned": 10066,
                "killingSprees": 0,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 15,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "firstInhibitorAssist": false,
                "perk0Var1": 434,
                "combatPlayerScore": 0,
                "perk0Var3": 124,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 1587,
                "totalMinionsKilled": 32,
                "timeCCingOthers": 0
            },
            "spell1Id": 4,
            "participantId": 3,
            "highestAchievedSeasonTier": "UNRANKED",
            "spell2Id": 21,
            "teamId": 100,
            "timeline": {
                "lane": "MIDDLE",
                "participantId": 3,
                "csDiffPerMinDeltas": {
                    "0-10": -0.3999999999999998
                },
                "goldPerMinDeltas": {
                    "0-10": 400.6
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -25.219999999999942
                },
                "creepsPerMinDeltas": {
                    "0-10": 0.8999999999999999
                },
                "xpPerMinDeltas": {
                    "0-10": 511
                },
                "role": "NONE",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 150.8
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 739.8
                }
            },
            "championId": 11
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 8332,
                "largestMultiKill": 2,
                "totalTimeCrowdControlDealt": 24,
                "longestTimeSpentLiving": 697,
                "perk1Var1": 915,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8014,
                "perk4": 9111,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 5,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 275,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "damageDealtToTurrets": 0,
                "physicalDamageDealtToChampions": 233,
                "damageDealtToObjectives": 0,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 0,
                "perk4Var1": 856,
                "totalDamageTaken": 14304,
                "perk4Var3": 0,
                "largestCriticalStrike": 641,
                "largestKillingSpree": 4,
                "quadraKills": 0,
                "magicDamageDealt": 15913,
                "item2": 2420,
                "item3": 3047,
                "item0": 3065,
                "item1": 3152,
                "item6": 2052,
                "item4": 3108,
                "item5": 0,
                "perk1": 8226,
                "perk0": 8214,
                "perk3": 8237,
                "perk2": 8210,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 489,
                "damageSelfMitigated": 13211,
                "magicalDamageTaken": 3703,
                "perk0Var2": 0,
                "firstInhibitorKill": false,
                "trueDamageTaken": 80,
                "assists": 4,
                "perk4Var2": 0,
                "goldSpent": 7900,
                "trueDamageDealt": 0,
                "participantId": 4,
                "physicalDamageDealt": 1300,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 8566,
                "physicalDamageTaken": 10521,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 17213,
                "deaths": 2,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8000,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 0,
                "goldEarned": 10421,
                "killingSprees": 1,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 16,
                "doubleKills": 2,
                "inhibitorKills": 0,
                "firstInhibitorAssist": false,
                "perk0Var1": 700,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 2849,
                "totalMinionsKilled": 15,
                "timeCCingOthers": 7
            },
            "spell1Id": 21,
            "participantId": 4,
            "highestAchievedSeasonTier": "GOLD",
            "spell2Id": 4,
            "teamId": 100,
            "timeline": {
                "lane": "MIDDLE",
                "participantId": 4,
                "csDiffPerMinDeltas": {
                    "0-10": -0.3999999999999998
                },
                "goldPerMinDeltas": {
                    "0-10": 383.8
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -25.219999999999942
                },
                "creepsPerMinDeltas": {
                    "0-10": 0.4
                },
                "xpPerMinDeltas": {
                    "0-10": 676.7
                },
                "role": "NONE",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 150.8
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 355.3
                }
            },
            "championId": 28
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 14244,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 170,
                "longestTimeSpentLiving": 347,
                "perk1Var1": 27,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8237,
                "perk4": 8224,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 8,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 14,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 687,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "damageDealtToTurrets": 372,
                "physicalDamageDealtToChampions": 8130,
                "damageDealtToObjectives": 372,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 37,
                "perk4Var1": 899,
                "totalDamageTaken": 36229,
                "perk4Var3": 0,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 4,
                "quadraKills": 0,
                "magicDamageDealt": 39613,
                "item2": 3065,
                "item3": 3068,
                "item0": 2051,
                "item1": 3009,
                "item6": 2052,
                "item4": 0,
                "item5": 0,
                "perk1": 8242,
                "perk0": 8437,
                "perk3": 8451,
                "perk2": 8430,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 195,
                "damageSelfMitigated": 43508,
                "magicalDamageTaken": 10683,
                "perk0Var2": 1263,
                "firstInhibitorKill": false,
                "trueDamageTaken": 130,
                "assists": 13,
                "perk4Var2": 0,
                "goldSpent": 7700,
                "trueDamageDealt": 5205,
                "participantId": 5,
                "physicalDamageDealt": 30146,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 24029,
                "physicalDamageTaken": 25416,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 74965,
                "deaths": 6,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8200,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 1655,
                "goldEarned": 11994,
                "killingSprees": 2,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 16,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "firstInhibitorAssist": false,
                "perk0Var1": 1718,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 7465,
                "totalMinionsKilled": 67,
                "timeCCingOthers": 16
            },
            "spell1Id": 4,
            "participantId": 5,
            "highestAchievedSeasonTier": "SILVER",
            "spell2Id": 32,
            "teamId": 100,
            "timeline": {
                "lane": "MIDDLE",
                "participantId": 5,
                "csDiffPerMinDeltas": {
                    "0-10": -0.3999999999999998
                },
                "goldPerMinDeltas": {
                    "0-10": 461.70000000000005
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -25.219999999999942
                },
                "creepsPerMinDeltas": {
                    "0-10": 2.8
                },
                "xpPerMinDeltas": {
                    "0-10": 612.4
                },
                "role": "NONE",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 150.8
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 995.3
                }
            },
            "championId": 36
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 13253,
                "largestMultiKill": 4,
                "totalTimeCrowdControlDealt": 215,
                "longestTimeSpentLiving": 339,
                "perk1Var1": 1183,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 1,
                "perk5": 8014,
                "perk4": 9111,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 12,
                "playerScore1": 1,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 756,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "damageDealtToTurrets": 139,
                "physicalDamageDealtToChampions": 2893,
                "damageDealtToObjectives": 139,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 31,
                "perk4Var1": 1524,
                "totalDamageTaken": 17546,
                "perk4Var3": 0,
                "largestCriticalStrike": 89,
                "largestKillingSpree": 4,
                "quadraKills": 1,
                "magicDamageDealt": 22022,
                "item2": 3145,
                "item3": 3151,
                "item0": 3100,
                "item1": 3144,
                "item6": 2052,
                "item4": 3158,
                "item5": 0,
                "perk1": 8139,
                "perk0": 8112,
                "perk3": 8135,
                "perk2": 8138,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 5,
                "damageSelfMitigated": 11341,
                "magicalDamageTaken": 7216,
                "perk0Var2": 0,
                "firstInhibitorKill": true,
                "trueDamageTaken": 910,
                "assists": 16,
                "perk4Var2": 0,
                "goldSpent": 9800,
                "trueDamageDealt": 0,
                "participantId": 6,
                "physicalDamageDealt": 7494,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 16147,
                "physicalDamageTaken": 9419,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 29517,
                "deaths": 6,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8000,
                "turretKills": 0,
                "firstBloodKill": true,
                "trueDamageDealtToChampions": 0,
                "goldEarned": 12448,
                "killingSprees": 3,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 17,
                "doubleKills": 2,
                "inhibitorKills": 1,
                "firstInhibitorAssist": false,
                "perk0Var1": 859,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 5083,
                "totalMinionsKilled": 23,
                "timeCCingOthers": 11
            },
            "spell1Id": 21,
            "participantId": 6,
            "highestAchievedSeasonTier": "UNRANKED",
            "spell2Id": 4,
            "teamId": 200,
            "timeline": {
                "lane": "MIDDLE",
                "participantId": 6,
                "csDiffPerMinDeltas": {
                    "0-10": 0.3999999999999998
                },
                "goldPerMinDeltas": {
                    "0-10": 525.8
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 25.219999999999942
                },
                "creepsPerMinDeltas": {
                    "0-10": 1.8
                },
                "xpPerMinDeltas": {
                    "0-10": 638.7
                },
                "role": "NONE",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -150.8
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 487.4
                }
            },
            "championId": 105
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 757,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 0,
                "longestTimeSpentLiving": 336,
                "perk1Var1": 2690,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8105,
                "perk4": 8138,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 8,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 5,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "damageDealtToTurrets": 736,
                "physicalDamageDealtToChampions": 28354,
                "damageDealtToObjectives": 736,
                "perk2Var2": 36,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 8,
                "perk4Var1": 18,
                "totalDamageTaken": 20013,
                "perk4Var3": 0,
                "largestCriticalStrike": 570,
                "largestKillingSpree": 4,
                "quadraKills": 0,
                "magicDamageDealt": 1306,
                "item2": 3184,
                "item3": 3046,
                "item0": 3508,
                "item1": 3006,
                "item6": 2052,
                "item4": 1037,
                "item5": 3036,
                "perk1": 9111,
                "perk0": 8005,
                "perk3": 8017,
                "perk2": 9104,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 1178,
                "damageSelfMitigated": 12115,
                "magicalDamageTaken": 7256,
                "perk0Var2": 1607,
                "firstInhibitorKill": false,
                "trueDamageTaken": 1133,
                "assists": 25,
                "perk4Var2": 0,
                "goldSpent": 11675,
                "trueDamageDealt": 0,
                "participantId": 7,
                "physicalDamageDealt": 77651,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 29112,
                "physicalDamageTaken": 11624,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 78958,
                "deaths": 6,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 0,
                "goldEarned": 12912,
                "killingSprees": 2,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 17,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "firstInhibitorAssist": true,
                "perk0Var1": 2260,
                "combatPlayerScore": 0,
                "perk0Var3": 652,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 4368,
                "totalMinionsKilled": 54,
                "timeCCingOthers": 0
            },
            "spell1Id": 21,
            "participantId": 7,
            "highestAchievedSeasonTier": "SILVER",
            "spell2Id": 4,
            "teamId": 200,
            "timeline": {
                "lane": "MIDDLE",
                "participantId": 7,
                "csDiffPerMinDeltas": {
                    "0-10": 0.3999999999999998
                },
                "goldPerMinDeltas": {
                    "0-10": 503
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 25.219999999999942
                },
                "creepsPerMinDeltas": {
                    "0-10": 1.6
                },
                "xpPerMinDeltas": {
                    "0-10": 593.5
                },
                "role": "NONE",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -150.8
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 779.4
                }
            },
            "championId": 15
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 4279,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 133,
                "longestTimeSpentLiving": 355,
                "perk1Var1": 4,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8430,
                "perk4": 8451,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 2,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 6,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "damageDealtToTurrets": 1071,
                "physicalDamageDealtToChampions": 689,
                "damageDealtToObjectives": 1071,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 4,
                "perk2Var1": 1,
                "perk4Var1": 112,
                "totalDamageTaken": 10374,
                "perk4Var3": 0,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 0,
                "quadraKills": 0,
                "magicDamageDealt": 14874,
                "item2": 0,
                "item3": 3100,
                "item0": 3089,
                "item1": 2031,
                "item6": 2052,
                "item4": 3024,
                "item5": 3801,
                "perk1": 8345,
                "perk0": 8326,
                "perk3": 8347,
                "perk2": 8321,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 0,
                "damageSelfMitigated": 7407,
                "magicalDamageTaken": 4084,
                "perk0Var2": 0,
                "firstInhibitorKill": false,
                "trueDamageTaken": 251,
                "assists": 24,
                "perk4Var2": 0,
                "goldSpent": 8700,
                "trueDamageDealt": 0,
                "participantId": 8,
                "physicalDamageDealt": 4409,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 4969,
                "physicalDamageTaken": 6039,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 19283,
                "deaths": 4,
                "perkPrimaryStyle": 8300,
                "perkSubStyle": 8400,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 0,
                "goldEarned": 10495,
                "killingSprees": 0,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 16,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "firstInhibitorAssist": true,
                "perk0Var1": 0,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 1965,
                "totalMinionsKilled": 27,
                "timeCCingOthers": 8
            },
            "spell1Id": 4,
            "participantId": 8,
            "highestAchievedSeasonTier": "UNRANKED",
            "spell2Id": 7,
            "teamId": 200,
            "timeline": {
                "lane": "MIDDLE",
                "participantId": 8,
                "csDiffPerMinDeltas": {
                    "0-10": 0.3999999999999998
                },
                "goldPerMinDeltas": {
                    "0-10": 432.3
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 25.219999999999942
                },
                "creepsPerMinDeltas": {
                    "0-10": 1.9
                },
                "xpPerMinDeltas": {
                    "0-10": 659.5
                },
                "role": "NONE",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -150.8
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 414.2
                }
            },
            "championId": 117
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 16763,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 298,
                "longestTimeSpentLiving": 444,
                "perk1Var1": 1032,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8105,
                "perk4": 8138,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 4,
                "playerScore1": 1,
                "playerScore0": 0,
                "playerScore3": 7,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 5,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "damageDealtToTurrets": 222,
                "physicalDamageDealtToChampions": 1270,
                "damageDealtToObjectives": 222,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 0,
                "perk4Var1": 30,
                "totalDamageTaken": 14478,
                "perk4Var3": 0,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 0,
                "quadraKills": 0,
                "magicDamageDealt": 43295,
                "item2": 3010,
                "item3": 3020,
                "item0": 2031,
                "item1": 3191,
                "item6": 2052,
                "item4": 3285,
                "item5": 3165,
                "perk1": 8226,
                "perk0": 8229,
                "perk3": 8236,
                "perk2": 8210,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 8,
                "damageSelfMitigated": 6939,
                "magicalDamageTaken": 6461,
                "perk0Var2": 0,
                "firstInhibitorKill": false,
                "trueDamageTaken": 394,
                "assists": 20,
                "perk4Var2": 0,
                "goldSpent": 9650,
                "trueDamageDealt": 345,
                "participantId": 9,
                "physicalDamageDealt": 2750,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 18334,
                "physicalDamageTaken": 7623,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 46391,
                "deaths": 6,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8100,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 300,
                "goldEarned": 10688,
                "killingSprees": 0,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 16,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "firstInhibitorAssist": true,
                "perk0Var1": 1471,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 1260,
                "totalMinionsKilled": 30,
                "timeCCingOthers": 28
            },
            "spell1Id": 32,
            "participantId": 9,
            "highestAchievedSeasonTier": "UNRANKED",
            "spell2Id": 4,
            "teamId": 200,
            "timeline": {
                "lane": "MIDDLE",
                "participantId": 9,
                "csDiffPerMinDeltas": {
                    "0-10": 0.3999999999999998
                },
                "goldPerMinDeltas": {
                    "0-10": 438.6
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 25.219999999999942
                },
                "creepsPerMinDeltas": {
                    "0-10": 0.7999999999999999
                },
                "xpPerMinDeltas": {
                    "0-10": 632.1
                },
                "role": "NONE",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -150.8
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 462
                }
            },
            "championId": 134
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 1383,
                "largestMultiKill": 2,
                "totalTimeCrowdControlDealt": 65,
                "longestTimeSpentLiving": 563,
                "perk1Var1": 898,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8236,
                "perk4": 8234,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 10,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 4,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "damageDealtToTurrets": 3404,
                "physicalDamageDealtToChampions": 24993,
                "damageDealtToObjectives": 3404,
                "perk2Var2": 36,
                "perk2Var3": 0,
                "totalUnitsHealed": 3,
                "perk2Var1": 8,
                "perk4Var1": 17,
                "totalDamageTaken": 16251,
                "perk4Var3": 0,
                "largestCriticalStrike": 1197,
                "largestKillingSpree": 4,
                "quadraKills": 0,
                "magicDamageDealt": 1915,
                "item2": 3031,
                "item3": 3085,
                "item0": 3184,
                "item1": 3006,
                "item6": 2052,
                "item4": 1053,
                "item5": 1038,
                "perk1": 9111,
                "perk0": 8005,
                "perk3": 8014,
                "perk2": 9104,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 819,
                "damageSelfMitigated": 7548,
                "magicalDamageTaken": 7073,
                "perk0Var2": 1240,
                "firstInhibitorKill": false,
                "trueDamageTaken": 944,
                "assists": 14,
                "perk4Var2": 0,
                "goldSpent": 10400,
                "trueDamageDealt": 0,
                "participantId": 10,
                "physicalDamageDealt": 73185,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 26377,
                "physicalDamageTaken": 8233,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 75101,
                "deaths": 5,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "turretKills": 2,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 0,
                "goldEarned": 12770,
                "killingSprees": 3,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": true,
                "champLevel": 16,
                "doubleKills": 2,
                "inhibitorKills": 0,
                "firstInhibitorAssist": true,
                "perk0Var1": 1588,
                "combatPlayerScore": 0,
                "perk0Var3": 348,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 3197,
                "totalMinionsKilled": 68,
                "timeCCingOthers": 29
            },
            "spell1Id": 4,
            "participantId": 10,
            "highestAchievedSeasonTier": "SILVER",
            "spell2Id": 7,
            "teamId": 200,
            "timeline": {
                "lane": "MIDDLE",
                "participantId": 10,
                "csDiffPerMinDeltas": {
                    "0-10": 0.3999999999999998
                },
                "goldPerMinDeltas": {
                    "0-10": 525.3
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 25.219999999999942
                },
                "creepsPerMinDeltas": {
                    "0-10": 3
                },
                "xpPerMinDeltas": {
                    "0-10": 681.9
                },
                "role": "NONE",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -150.8
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 546.9
                }
            },
            "championId": 51
        }
    ],
    "gameDuration": 1141,
    "gameCreation": 1514092286027
};